#v1
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: k8s-multi-com-tls
spec:
  secretName: k8s-multi-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: k8s.dataplus.ru
  dnsNames:
    - k8s.dataplus.ru
    - www.k8s.dataplus.ru
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - k8s.dataplus.ru
          - www.k8s.dataplus.ru